dataset: pems8
node_num: 170
window_size: 864
max_thres: 1
test_rate: 0.1
in_features: 1
out_features: 32
lstm_features: 128
disc_hidden: 512
pretrain_learning_rate: 0.005
d_learning_rate: 0.00001
g_learning_rate: 0.00001
batch_size: 16
pretrain_epoches: 5
gan_epoches: 3
gradient_clip: 5.0
weight_clip: 0.01
epsilon: 0.01